twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        school_name: '%school_name%'
        moto: '%moto%'
        vision: '%vision%'
        mission: '%mission%'
        email: '%email%'
        contact: '%contact%'
