twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        email: '%email%'
        contact: '%contact%'
        settings: '@App\EventSubscriber\SettingsValuesSubscriber'
