
parameters:
    locale: 'en'
    locale_fallback: 'fr'
    student_photos_directory: 'assets/images/students_profiles/'
    secret: '%env(resolve:APP_ENV)%'
    school_name: 'Mt. George SS'
    moto: 'Knowledge has no limit'
    vision: ''
    mission: ''
    email: email@myschool.com
    contact: ''
