
fos_user.registration:
    path: /register/
    controller: App\Controller\RegistrationController::registerAction

fos_user.resetting.request:
    path: /resetting/send-email
    controller: App\Controller\ResettingController::sendEmailAction

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
